INSERT INTO students (name, course, age, city) VALUES
('Adam', 'golang', 25, 'New York'),
('Brian', 'python', 22, 'London'),
('Chris', 'javascript', 20, 'New York'),
('Dan', 'java', 25, 'London'),
('Eve', 'python', 22, 'New York'),
('Frank', 'java', 25, 'London'),
('Grace', 'python', 22, 'New York'),
('Hank', 'java', 25, 'London'),
('Ivy', 'python', 22, 'New York'),
('Jack', 'java', 25, 'London'),
('Jill', 'python', 22, 'New York'),
('John', 'java', 25, 'London'),
('Julia', 'python', 22, 'New York'),
('Juliet', 'java', 25, 'London'),
('Julius', 'python', 22, 'New York'),
('June', 'java', 25, 'London'),
('July', 'python', 22, 'New York'),
('August', 'java', 25, 'London'),
('September', 'python', 22, 'New York'),
('October', 'java', 25, 'London'),
('November', 'python', 22, 'New York'),
('December', 'java', 25, 'London');